### ISSUE TITLE
Не работает redirect 

### ISSUE THREAD

**Issue by ruddy22** [GarikProg/Link-shortener#2]
Приветствую, @GarikProg !

Не работает переход по укороченной ссылке. 

Шаги для воспроизведения:
1. Создал ссылку в вашем приложении
![image](https://user-images.githubusercontent.com/1384247/100105326-472cbe80-2e78-11eb-89ed-ca5311231eaf.png)
2. скопировал адрес и забиваю его в адресную строку
![image](https://user-images.githubusercontent.com/1384247/100105500-7e9b6b00-2e78-11eb-8bf7-57997cd07a64.png)
3. получаю json из базы, вместо целевого адреса ya.ru
![image](https://user-images.githubusercontent.com/1384247/100105616-9ffc5700-2e78-11eb-83fa-be9df57502cf.png)

**Comment by GarikProg** [comment]
Я могу переделать, там в indexRouter, вместо res.json надо написать
res.redirect(shortLink)

вт, 24 нояб. 2020 г., 17:15 Aleksey Petrov <notifications@github.com>:

**Comment by GarikProg** [comment]
longLink вместо shorLink

вт, 24 нояб. 2020 г., 17:29 Igor kozlov <kozlovigor1989@gmail.com>:

**Comment by GarikProg** [comment]
Алексей, я добрался до компьютера и исправил и залил на GitHub. Посмотрите
пожалуйста.
Строчку
res.status(200).json(link);
заменил на:
res.redirect(link.longLink);

вт, 24 нояб. 2020 г. в 17:30, Igor kozlov <kozlovigor1989@gmail.com>:

**Comment by ruddy22** [comment]
Отлично! Спасибо!
